export * from './common.schema';
export * from './user.schema';
export * from './student.schema';
export * from './course.schema';
export * from './score.schema';
export * from './grading.schema';
export * from './scaling.schema';
export * from './result.schema';
export * from './audit.schema';
